name: eitherx
description: Either provides a way to handle errors and exceptions in a more expressive and concise way

version: 2.0.1
repository: https://github.com/hasanmhallak/Either

environment:
  sdk: ">=2.19.2 <4.0.0"

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
